[package]
name = "yew-example"
edition = "2024"
version = "0.1.0"
license = "MIT"

[dependencies]
# Use path to local SDK
telegram-webapp-sdk = { path = "/home/ra/Projects/telegram-webapp-sdk", features = ["macros"] }
telegram-ui = { path = "..", features = ["yew"] }
yew = { version = "0.23", features = ["csr"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
